spring.application.name=AiStudentManagementSystem

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/AiStudent
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Spring AI - Google Gemini
# ==============================
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-3.6-flash